# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Azure-Tansit-VNET
# label used for menu selection
label: Azure Transit VNET Framework. Step 1 - Infrastructure Deployment & Step 6 - Infrastructure Destroy
description: >
              Step 1 - This skillet deploys Azure Hub and Spoke architecture that consist of VM-Series Azure Load Balancing Sandwich deployment in Hub VNET and one Spoke VNET's with test instances.
              The template deploys the Following:
              Azure VNET's, Route Tables, Subnet's, Availability Zones, Load Balancers and VNET Peering.
              The Template will also deploy Palo Alto Networks Firewalls.
              Step 6 - Uses Terraform Destroy process to delete the deployment by removing Firewalls and all Azure components (VNET's, Instances, LB's, Resource Group, etc.).
# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: terraform
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Azure-Tansit-VNET

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: adminuser
    description: FW, Web, Dev Username
    default: panadmin
    type_hint: text
  - name: adminuserpassword
    description: FW, Web, Dev Password
    default: PanPassword123!
    type_hint: password
  - name: resource_group
    description: Azure Resource Group
    default: transit-vnet-demo-changeme
    type_hint: text
  - name: location
    description: Azure Region
    default: centralus
    type_hint: dropdown
    dd_list:
     - key: "West US"
       value: "westus"
     - key: "West US 2"
       value: "westus2"
     - key: "West Central US"
       value: "westcentralus"
     - key: "East US"
       value: "eastus"
     - key: "East US 2"
       value: "eastus2"
     - key: "Central US"
       value: "centralus"
     - key: "North Central US"
       value: "northcentralus"
     - key: "South Central US"
       value: "southcentralus"
     - key: "Canada Central"
       value: "canadacentral"
     - key: "Canada East"
       value: "canadaeast"
     - key: "UK West"
       value: "ukwest"
     - key: "UK South"
       value: "uksouth"
     - key: "North Europe"
       value: "northeurope"
     - key: "West Europe"
       value: "westeurope"
     - key: "Australia East"
       value: "australiaeast"
     - key: "Australia Southeast"
       value: "australiasoutheast"
     - key: "Australia Central"
       value: "australiacentral"
     - key: "Australia Central 2"
       value: "australiacentral2"
     - key: "East Asia"
       value: "eastasia"
     - key: "South East Asia"
       value: "southeastasia"
     - key: "Korea Central"
       value: "koreacentral"
     - key: "Korea South"
       value: "koreasouth"
     - key: "Japan West"
       value: "japanwest"
     - key: "Japan East"
       value: "japaneast"
     - key: "South India"
       value: "southindia"
     - key: "Central India"
       value: "centralindia"
     - key: "West India"
       value: "westindia"
     - key: "Brazil South"
       value: "brazilsouth"
     - key: "France Central"
       value: "francecentral"
     - key: "France South"
       value: "francesouth"
  - name: vnet_cidr
    description: HUB VNET Space (i.e. transit-vnet 10.0.0.0/16)
    default: 10.0.0.0/16
    type_hint: cidr
  - name: subnet0_cidr
    description: FW-Management Subnet Space (i.e. 10.0.0.0/24)
    default: 10.0.0.0/24
    type_hint: cidr
  - name: subnet1_cidr
    description: UnTrust Subnet Space (i.e. 10.0.1.0/24)
    default: 10.0.1.0/24
    type_hint: cidr
  - name: subnet2_cidr
    description: Trust Subnet Space (i.e. 10.0.2.0/24)
    default: 10.0.2.0/24
    type_hint: cidr
  - name: subnet3_cidr
    description: LB-Subnet Space (i.e. 10.0.3.0/24)
    default: 10.0.3.0/24
    type_hint: cidr
  - name: spoke1-vnet_cidr
    description: Spoke1 VNET Space (i.e. transit-vnet 10.1.0.0/16)
    default: 10.1.0.0/16
    type_hint: cidr
  - name: subnet10_cidr
    description: Web Subnet Space (i.e. 10.1.0.0/24)
    default: 10.1.0.0/24
    type_hint: cidr
  - name: subnet11_cidr
    description: App Subnet Space (i.e. 10.0.1.0/24)
    default: 10.1.1.0/24
    type_hint: cidr
  - name: subnet12_cidr
    description: DB Subnet Space (i.e. 10.0.2.0/24)
    default: 10.1.2.0/24
    type_hint: cidr
  - name: subnet13_cidr
    description: Dev Subnet Space (i.e. 10.0.3.0/24)
    default: 10.1.3.0/24
    type_hint: cidr
  - name: egresslb_ip
    description: Internal Egress LB FrontEnd IP (IP must be part of LB-Subnet space i.e. 10.0.3.100)
    default: 10.0.3.100
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
#snippets:
  #- name: edl
  # xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/external-list
  #  file: edl.xml
  #- name: tag
  #  xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
  #  file: tag.xml
  #- name: security_rules
  #  xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
  #  file: in_security_rules.xml
# ---------------------------------------------------------------------
# end of snippets section
