# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Azure-Tansit-VNET-Inbound
# label used for menu selection
label: Azure Transit VNET Framework. Step 3 - Inbound Traffic Inspection
description: >
               This skillet demonstrates Inbound traffic inspection thru Hub NGFW’s by configuring Azure UDR’s and corresponding routes, NAT and security policies on VM-Series
# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Azure-Tansit-VNET

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: public_lb_ip
    description: Public Load Balancer Public Frontend IP
    default:
    type_hint: text
  - name: web1_ip
    description: Web server Web1 IP
    default: 10.1.0.4
    type_hint: text
  - name: security_policy_name
    description: Inbound security policy name
    default: allow-web-in
    type_hint: text
  - name: nat_policy_name
    description: Inbound NAT policy name
    default: inbound-nat-to-web1
    type_hint: text

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: address_objects
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
    file: address_objects.xml
  - name: in_security_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
    file: in_security_rules.xml
  - name: in_nat_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/nat/rules
    file: in_nat_rules.xml
# ---------------------------------------------------------------------
# end of snippets section
